### ISSUE TITLE
QC reliability 

### ISSUE THREAD

**Issue by AMA-cs** [Weeks-UNC/shapemapper2#42]
Hello, 

I've been using shapemapper2 for processing my samples. My samples passed all the QC checks except one that always fail (Number highly reactive check):

![image](https://user-images.githubusercontent.com/17438932/217009881-42ae9045-79a7-40a4-aa24-d73970497231.png)

As you can see in the screenshot, all the other checks are good. For **_high background check_**, the background is very low, which we saw in previous samples, and that's why we increased the reagent 1M7 for this sample hoping to pass the last check and get higher number of highly reactive nucleotides. Unfortunately, it didn't pass the check. I discussed the possible causes with the lab staff, who are running the experiments, but they eliminated most of them.

I'm wondering how reliable this check is, or how generalized it can be to assess the samples considering the different types of RNA? Also, our initial plan is to keep increasing the reagent concentration until we get enough reactivity while monitoring the background check. I'm looking for any insight/recommendations/suggestions to figure out how to improve our data quality experimentally or computationally.

Thank you

**Comment by Psirving** [comment]
90% of nucleotides have a mutation rates above background. This suggests that your 1M7 is working fine. I suspect the last possible cause: extremely highly structured RNA. Could you attach your reactivity profile pdf?

**Comment by AbeerMM** [comment]
@Psirving Thank you so much for your quick response. Attached is the pdf file for this specific sample. 
[mRNA_profiles.pdf](https://github.com/Weeks-UNC/shapemapper2/files/10667729/mRNA_profiles.pdf)

However, for this QC. It failed with RNAs that we think they are not really highly structures. That's why I'm puzzled. 

Thank you

**Comment by Psirving** [comment]
This is not an exceptionally highly structured RNA. It is likely failing because your reactivity rates are low.

If these are in-cell modifications, it could be that the reagent is not penetrating very well. It could also mean that your 1M7 is impure or partially degraded. 2A3 and NAI are reagents that produce reliably higher mutation rates and permeate cells better than 1M7.

You could try again with one of these reagents, or you could proceed. This data looks sufficiently high quality to produce good structure models.

**Comment by AbeerMM** [comment]
@Psirving This is extremely helpful. Thank you so much.
Our data is not in-cell. According to the lab person cell-free is the most relevant. I'm wondering if any of the points you mentioned still applied in this case?

Also, since our data is not in-cell, do you think if we keep increasing the reagent concentration, we might get higher reactivity rates eventually?
 
 I think I will proceed with the current batch of data to generate structure models. 

Thanks again
